theme: jekyll-theme-slate
title: Easy Nails VIPs
description: Hi! I'm Amy Shelton, a Color Street independent stylist. Welcome to my VIP website where you'll find links to shop for Color Street nail sets and social media where you can connect with fellow Color Street enthusiasts, hang out, and have fun.
showdownloads: false
