theme: jekyll-theme-slate
title: Easy Nails VIPs
description: Hi! I'm Amy Shelton and I'm an independent stylist for Color Street. Welcome to my VIP website where you'll find links to shop for Color Street nail sets and to my Facebook VIP page where fellow Color Street enthusiasts hang out and have fun.
showdownloads: false
